<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPMDKhBm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPMDKhBm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPMDKhBm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPMDKhBm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPMDKhBm\App_KernelDevDebugContainer([
    'container.build_hash' => 'PMDKhBm',
    'container.build_id' => '471ac477',
    'container.build_time' => 1685538183,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPMDKhBm');
