<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAwapbDu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAwapbDu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAwapbDu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAwapbDu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAwapbDu\App_KernelDevDebugContainer([
    'container.build_hash' => 'AwapbDu',
    'container.build_id' => 'ad58582f',
    'container.build_time' => 1685488515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAwapbDu');
