<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRJm5zJP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRJm5zJP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRJm5zJP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRJm5zJP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRJm5zJP\App_KernelDevDebugContainer([
    'container.build_hash' => 'RJm5zJP',
    'container.build_id' => '1991c2af',
    'container.build_time' => 1685361252,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRJm5zJP');
